# -*- coding: utf-8 -*-
"""Trading_Main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TeHBSMy8ntsAmzV2Nqj3VPAGx0AtbCF3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader.data as web
import datetime

class account():
    
  def __init__(self,money,time,StockData,AbleToShort=True,BorrowToBuy=True,PrintRecord=True):
    self.money=money
    self.time=time
    self.start_time=time
    self.stocks=pd.DataFrame([],columns=['stock','volume'])
    self.AbleToShort=AbleToShort
    self.TradeRecord=pd.DataFrame([],columns=['time','Buy|Sell','stock','price','volume','money','asset'])
    self.MoneyRecord=pd.DataFrame([[money]],columns=['money'])
    self.StockData=StockData
    self.TimeLine=self.StockData[list(self.StockData.keys())[0]].loc[self.start_time:].index.values
    self.TimeIndex=0
    self.PrintRecord=PrintRecord
    self.BorrowToBuy=BorrowToBuy


  def IncementDay(self,i=1):
    #i=1 means going to the next trading day
    self.TimeIndex+=i
    self.time=self.TimeLine[self.TimeIndex]

  def CheckDate(self,incre=0):
    #0 means to check today's date
    incre=self.TimeIndex+incre
    return self.TimeLine[incre]

  def UpdateMoney(self):
    new_row=pd.DataFrame({'money':self.CheckMoney()}).set_index(pd.index([len(self.MoneyRecord)]))
    self.MoneyRecord.append(new_row)
    return self.MoneyRecord

  def CheckAccount(self):
    return self.stocks,self.money

  def CheckMoney(self):
    return self.money

  def Buy(self,stock,volume,price=None,time=None):
    if price==None:
      price=self.CheckCurrentValue(stock,'Adj Close')
    if time==None:
      time=self.time
    if self.BorrowToBuy==False and self.money<price*volume:
      print("Can't buy with no money")
      return 0
      
    else:
      self.money=self.money-price*volume
      self.MoneyRecord.append(pd.DataFrame([[self.money]],columns=['money']))
      if stock in self.stocks['stock'].values:
        index=self.stocks.index[self.stocks['stock'] == stock].tolist()[0]
        self.stocks.loc[index]['volume']+=volume
      else:
        self.stocks=self.stocks.append(pd.DataFrame([[stock,volume]],columns=['stock','volume']))
        self.stocks=self.stocks.set_index(np.arange(0,self.stocks.shape[0]))
      if self.PrintRecord==True:
        txt='{} Bought {} shares of {} stock at price {}'.format(self.time,volume,stock,price)
        print(txt)
      self.TradeRecord=self.TradeRecord.append(pd.DataFrame([[time,'Buy',stock,price,volume,self.money,self.TotalAsset()]],columns=['time','Buy|Sell','stock','price','volume','money','asset']))

  def Sell(self,stock,volume,price=None,time=None):
    if price==None:
      price=self.CheckCurrentValue(stock,'Adj Close')
    if time==None:
      time=self.time
    if self.AbleToShort==True:
      self.money=self.money+price*volume
      self.MoneyRecord.append(pd.DataFrame([[self.money]],columns=['money']))
      if stock in self.stocks['stock'].values:
        
        index=self.stocks.index[self.stocks['stock'] == stock].tolist()[0]
        self.stocks.loc[index]['volume']-=volume
        
      else:
        
        self.stocks=self.stocks.append(pd.DataFrame([[stock,-volume]],columns=['stock','volume']))
        self.stocks=self.stocks.set_index(np.arange(0,self.stocks.shape[0]))

      if self.PrintRecord==True:
        txt='{} Sold {} shares of {} stock at price {}'.format(self.time,volume,stock,price)
        print(txt)
      self.TradeRecord=self.TradeRecord.append(pd.DataFrame([[time,'Sell',stock,price,-volume,self.money,self.TotalAsset()]],columns=['time','Buy|Sell','stock','price','volume','money','asset']))
      
    if self.AbleToShort==False:
      if stock in self.stocks['stock'].values:
        index=self.stocks.index[self.stocks['stock'] == stock].tolist()[0]
        if self.stocks.loc[index]['volume']>=volume:
          self.stocks.loc[index]['volume']-=volume
          self.money=self.money+price*volume
          self.MoneyRecord.append(pd.DataFrame([[self.money]],columns=['money']))
          
          if self.PrintRecord==True:
            txt='{} Sold {} shares of {} stock at price {}'.format(self.time,volume,stock,price)
            print(txt)
          self.TradeRecord=self.TradeRecord.append(pd.DataFrame([[time,'Sell',stock,price,-volume,self.money,self.TotalAsset()]],columns=['time','Buy|Sell','stock','price','volume','money','asset']))
            
        else:
          print('Not able to sell stocks you do not have')
          return 0
      else:
        print('Not able to sell stocks you do not have')
        return 0

  def TotalAsset(self,time=None):
    if time==None:
      time=self.time
    StockAsset=0
    for i in range(self.stocks.shape[0]):
      stock=self.stocks.iloc[i]['stock']
      price=self.StockData[stock].loc[time]['Adj Close']
      StockAsset+=price*self.stocks.iloc[i]['volume']
    return self.money+StockAsset
  
  def Clear(self):
    for i in range(self.stocks.shape[0]):
      stock=self.stocks.iloc[i]['stock']
      volume=self.stocks.iloc[i]['volume']
      if volume>0.0:
        self.Sell(stock,volume)
      if volume<0.0:
        self.Buy(stock,-volume)
      
      
    return 0

  ##Close a position composed of exactly two stocks
  def Close(self,StockName):
    i=StockName[0]
    g=StockName[1]
    
  
      
    df=self.stocks.loc[((self.stocks['stock']==i) | (self.stocks['stock']==g))]
    df=df.sort_values('volume',ascending=False)
    for j in range(len(df.index)):
      stock=df.iloc[j]['stock']
      volume=df.iloc[j]['volume']

      if volume>0.0:
        self.Sell(stock,volume)
      if volume<0.0:
        self.Buy(stock,-volume)
    return 0

  
  
  def CheckCurrentValue(self,stock,value='Adj Close'):

    return self.StockData[stock].loc[self.time][value]

  def ShowTradeRecord(self):
    self.TradeRecord=self.TradeRecord.set_index(np.arange(0,self.TradeRecord.shape[0]))
    return self.TradeRecord
  
  def CheckValue(self,stock,time,variable):
    return self.StockData['stock'].loc[time][variable]

  


          
          

